server:
  port: 9005
spring:
  application:
    name: zyg-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.17:3306/zyg_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.56.17
  redis:
    host: 192.168.56.17
  cloud:
    sentinel:
      web-context-unify: false
      transport:
        port: 8719
        dashboard: localhost:8088
      block-page: /flow/blockPage
#      filter:
#        enabled: false
#

logging:
  level:
    com.zyg.user: debug
feign:
#  hystrix:
#    enabled: true
  sentinel:
    enabled: true
